# Platform
TARGET_BOARD_PLATFORM := sc8830
TARGET_BOARD_PLATFORM_GPU := mali-400
TARGET_GLOBAL_CFLAGS += -mtune=cortex-a7 -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mtune=cortex-a7 -mfpu=neon -mfloat-abi=softfp
TARGET_BUILD_VARIANT=user

# Architecture
ARCH_ARM_HAVE_NEON := true # Take advantage of arm-neon optimisation
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a7
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a7


# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := grandprimeve3g

# Kernel
TARGET_KERNEL_CONFIG := cyanogen_grandprimeve3g_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/sprd

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1572864000
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200

BOARD_CACHE_DEVICE := /dev/block/mmcblk0p24
BOARD_CACHE_FILESYSTEM := ext4
BOARD_CACHE_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p25
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_DATA_DEVICE := /dev/block/mmcblk0p27
BOARD_DATA_FILESYSTEM := ext4
BOARD_DATA_FILESYSTEM_OPTIONS := rw

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_RECOVERY_NEEDS_FBIOPAN_DISPLAY:=true
DEVICE_RESOLUTION := 540x960
HAVE_SELINUX := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_RECOVERY_FSTAB := device/samsung/grandprimeve3g/recovery.fstab

# TWRP specifics
TW_THEME := portrait_mdpi
TWHAVE_SELINUX := true
TW_HAVE_X86_ACCELERATED_PIXELFLINGER := false
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_NO_SCREEN_BLANK := true # Only use this flag when you have sc8830
TW_NO_SCREEN_TIMEOUT := true
TW_NO_CPU_TEMP := true
TW_NO_REBOOT_BOOTLOADER := true
TW_MTP_DEVICE := /dev/usb_mtp_gadget
TW_INCLUDE_FB2PNG := true # A better way to take screenshot
TW_INCLUDE_NTFS_3G := true
TW_EXCLUDE_SUPERSU := true # Lol we hate this prompt anyway
TW_NEVER_UNMOUNT_SYSTEM := true
TW_INCLUDE_L_CRYPTO := true
TW_HAS_DOWNLOAD_MODE := true
PLATFORM_SDK_VERSION := 22
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := en-US # Sorry clarc, but English is the international language
TW_USE_TOOLBOX := true # Cuz why not
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/20200000.usb/gadget/lun%d/file"
