add_lunch_combo grandprimeve3gxx-user
add_lunch_combo grandprimeve3gxx-userdebug
add_lunch_combo grandprimeve3gxx-eng
add_lunch_combo omni_grandprimeve3gxx-user
add_lunch_combo omni_grandprimeve3gxx-userdebug
add_lunch_combo omni_grandprimeve3gxx-eng
